import { SERVER_CONFIG } from "./env";

const { BASE_URL } = SERVER_CONFIG;

export const API_ROUTES = {
  // ANALYZER: `${BASE_URL}/${process.env.NEXT_PUBLIC_ANALYZER_API_ROUTE}`,
  // SUMMARIZER: `${BASE_URL}/${process.env.NEXT_PUBLIC_SUMMARIZER_API_ROUTE}`,
  // TRANSLATOR: `${BASE_URL}/${process.env.NEXT_PUBLIC_TRANSLATOR_API_ROUTE}`,
  // FACT_CHECKER: `${BASE_URL}/${process.env.NEXT_PUBLIC_FACT_CHECKER_API_ROUTE}`,
  // DEEP_CHAT: `${BASE_URL}/${process.env.NEXT_PUBLIC_DEEP_CHAT_API_ROUTE}`,
  // INTERROGATOR: `${BASE_URL}/${process.env.NEXT_PUBLIC_INTERROGATOR_API_ROUTE}`,
  // COLLAB: `${BASE_URL}:${process.env.NEXT_PUBLIC_COLLAB_API_PORT}/api/v1`,

  ANALYZER: `${BASE_URL}/${SERVER_CONFIG.API_ROUTES.ANALYZER}`,
  SUMMARIZER: `${BASE_URL}/${SERVER_CONFIG.API_ROUTES.SUMMARIZER}`,
  TRANSLATOR: `${BASE_URL}/${SERVER_CONFIG.API_ROUTES.TRANSLATOR}`,
  FACT_CHECKER: `${BASE_URL}/${SERVER_CONFIG.API_ROUTES.FACT_CHECKER}`,
  DEEP_CHAT: `${BASE_URL}/${SERVER_CONFIG.API_ROUTES.DEEP_CHAT}`,
  INTERROGATOR: `${BASE_URL}/${SERVER_CONFIG.API_ROUTES.INTERROGATOR}`,
  COLLAB: `${BASE_URL}:${SERVER_CONFIG.PORTS.COLLAB}/api/v1`,
};

export const FRONTEND_ROUTES = {
  // ADMIN: `${BASE_URL}:${process.env.NEXT_PUBLIC_ADMIN_PORT}`,
  // ANALYZER: `${BASE_URL}:${process.env.NEXT_PUBLIC_ANALYZER_PORT}`,
  // SUMMARIZER: `${BASE_URL}:${process.env.NEXT_PUBLIC_SUMMARIZER_PORT}`,
  // TRANSLATOR: `${BASE_URL}:${process.env.NEXT_PUBLIC_TRANSLATOR_PORT}`,
  // FACT_CHECKER: `${BASE_URL}:${process.env.NEXT_PUBLIC_FACT_CHECKER_PORT}`,
  // DEEP_CHAT: `${BASE_URL}:${process.env.NEXT_PUBLIC_DEEP_CHAT_PORT}`,
  // INTERROGATOR: `${BASE_URL}:${process.env.NEXT_PUBLIC_INTERROGATOR_PORT}`,
  // COLLAB: `${BASE_URL}:${process.env.NEXT_PUBLIC_COLLAB_PORT}`,

  ADMIN: `${BASE_URL}:${SERVER_CONFIG.PORTS.ADMIN}`,
  ANALYZER: `${BASE_URL}:${SERVER_CONFIG.PORTS.ANALYZER}`,
  SUMMARIZER: `${BASE_URL}:${SERVER_CONFIG.PORTS.SUMMARIZER}`,
  TRANSLATOR: `${BASE_URL}:${SERVER_CONFIG.PORTS.TRANSLATOR}`,
  FACT_CHECKER: `${BASE_URL}:${SERVER_CONFIG.PORTS.FACT_CHECKER}`,
  DEEP_CHAT: `${BASE_URL}:${SERVER_CONFIG.PORTS.DEEP_CHAT}`,
  INTERROGATOR: `${BASE_URL}:${SERVER_CONFIG.PORTS.INTERROGATOR}`,
  COLLAB: `${BASE_URL}:${SERVER_CONFIG.PORTS.COLLAB}`,
};
